kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: console-volume
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
