apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: ignite-cluster
  namespace: default
spec:
  selector:
    matchLabels:
      app: ignite
  serviceName: ignite
  replicas: 2
  template:
    metadata:
      labels:
        app: ignite
    spec:
      serviceAccountName: ignite
      containers:
      - name: ignite-node
        image: apacheignite/ignite:2.5.0
        resources:
          limits:
            cpu: 500m 
            memory: 1000Mi
        env:
        - name: NAMESPACE # It is used in XML-config as TcpDiscoveryKubernetesIpFinder.namespace.
          value: "default"
        - name: SERVICENAME # It is used in XML-config as TcpDiscoveryKubernetesIpFinder.serviceName.
          value: "ignite"
        - name: WORKDIR # It is used in XML-config as IgniteConfiguration.workDirectory.
          value: "/data/ignite"
        - name: OPTION_LIBS
          value: ignite-kubernetes,ignite-rest-http
        - name: CONFIG_URI
          value: https://storage.googleapis.com/grid-configs/temp/gce/pds-config-1.xml
        - name: IGNITE_QUIET
          value: "false"
        - name: JVM_OPTS
          value: "-Xms300m -Xmx300m -Djava.net.preferIPv4Stack=true"
        ports:
        - containerPort: 11211 # JDBC port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 8080 # REST port number.
        volumeMounts:
        - mountPath: "/data/ignite"
          name: pds-storage
  volumeClaimTemplates:
  - metadata:
      name: pds-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

