apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ignite-cluster
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ignite
    spec:
      serviceAccountName: ignite
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        image: gromtech/ignite:2.6.0
        resources:
          limits:
            cpu: 500m 
            memory: 1000Mi
        env:
        - name: NAMESPACE # It is used in XML-config as TcpDiscoveryKubernetesIpFinder.namespace.
          value: "default"
        - name: SERVICENAME # It is used in XML-config as TcpDiscoveryKubernetesIpFinder.serviceName.
          value: "ignite"
        - name: OPTION_LIBS
          value: ignite-kubernetes,ignite-rest-http
        - name: CONFIG_URI
          value: https://storage.googleapis.com/grid-configs/temp/gce/default-config-1.xml
        - name: IGNITE_QUIET
          value: "false"
        - name: JVM_OPTS
          value: "-Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true"
        ports:
        - containerPort: 11211 # REST port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 8080 # SQL port number.

