apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: ignite-endpoint-access 
  namespace: default 
  labels: 
    app: ignite 
rules: 
  - apiGroups: [""] 
    resources: ["endpoints"] 
    resourceNames: ["ignite"] 
    verbs: ["get"]

