apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: ignite-role-binding 
  namespace: default 
  labels: 
    app: ignite 
subjects: 
  - kind: ServiceAccount 
    name: ignite 
roleRef: 
  kind: Role 
  name: ignite-endpoint-access 
  apiGroup: rbac.authorization.k8s.io
